// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Backend-reported usage recorded since tracking was enabled, including spawned agents.
 * One AI credit is 1,000,000,000 nano AIU. Usage is not an invoice or an amount owed.
 */
export type ThreadCopilotUsageReadResponse = { nanoAiu: bigint,
/**
 * API-equivalent USD in billionths, only for responses without a backend charge.
 * Null means no estimates are available. Add to the USD value of nano_aiu.
 */
estimatedNanoUsd: bigint | null, responses: bigint,
/**
 * Some attempts have neither a backend charge nor a usable token estimate.
 */
partial: boolean, pending: boolean, };
