// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Backend-reported usage recorded since tracking was enabled, including spawned agents.
 * One AI credit is 1,000,000,000 nano AIU. Usage is not an invoice or an amount owed.
 */
export type ThreadCopilotUsageReadResponse = { nanoAiu: bigint, responses: bigint, partial: boolean, pending: boolean, };
